---
- name: Get node pool
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    kind: NodePool
    namespace: "{{ nodepool_namespace }}"
  register: nodepoolinfo

- name: Create performance profile config map
  kubernetes.core.k8s:
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ performance_configmap_name }}"
        namespace: "{{ nodepool_namespace }}"
      data:
        tuning: |
           apiVersion: performance.openshift.io/v2
           kind: PerformanceProfile
           metadata:
             name: "{{ performance_profile_name }}"
           spec:
             cpu:
               isolated: 1,3-55,57,59-111
               reserved: 0,2,56,58
             hugepages:
               defaultHugepagesSize: 1G
               pages:
               - count: 1
                 node: 0
                 size: 1G
               - count: 128
                 node: 1
                 size: 2M
             nodeSelector:
               node-role.kubernetes.io/worker: ""
             numa:
               topologyPolicy: single-numa-node
             realTimeKernel:
               enabled: false
             workloadHints:
               highPowerConsumption: true
               perPodPowerManagement: false
               realTime: true

- name: Apply configmap to nodepool
  kubernetes.core.k8s:
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    state: present
    definition:
      apiVersion: hypershift.openshift.io/v1beta1
      kind: NodePool
      metadata:
        name: "{{ nodepoolinfo.resources[0].metadata.name }}"
        namespace: "{{ nodepool_namespace }}"
      spec:
        tuningConfig:
          - name: "{{ performance_configmap_name }}"

- name: Check if Nodepool is updating
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: NodePool
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    name: "{{ nodepoolinfo.resources[0].metadata.name }}"
    namespace: "{{ nodepool_namespace }}"
  register: nodepool_updating
  until:
    - "'resources' in nodepool_updating"
    - nodepool_updating.resources | length > 0
    - nodepool_updating.resources[0].status.conditions | json_query("[?type=='UpdatingConfig' && status=='True']") | length > 0
  retries: 10
  delay: 20

- name: Check if Nodepool is updated
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: NodePool
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    name: "{{ nodepoolinfo.resources[0].metadata.name }}"
    namespace: "{{ nodepoolinfo.resources[0].metadata.namespace }}"
  register: nodepool_updated
  until:
    - "'resources' in nodepool_updated"
    - nodepool_updated.resources | length > 0
    - nodepool_updated.resources[0].status.conditions | json_query("[?type=='UpdatingConfig' && status=='False']") | length > 0
  retries: 80
  delay: 20

- name: Lets wait for 10 min to settle
  ansible.builtin.pause:
    minutes: 10
